### ISSUE TITLE
Release latest bugfixes

### ISSUE THREAD

**Issue by altrunner** [squix78/json-streaming-parser#13]
Would you mind releasing a new version of library so platformio can pick it up? I try to use this library but platformio only knows about version 1.0.4 which still contains the end document bug.
Thank you!

**Comment by squix78** [comment]
Is the bug you are referring to fixed?

**Comment by altrunner** [comment]
Sure.
Here is the merged pull request:
https://github.com/squix78/json-streaming-parser/commit/531870ac432e5c240706fc854e28d4b3222d4926

**Comment by squix78** [comment]
Great! I released 1.0.5. Can you keep an eye if platformio is picking it up and close this issue once you see it? Thanks!

**Comment by altrunner** [comment]
Thank you!
Sure, will do.

**Comment by altrunner** [comment]
Version 1.0.5 picked up by Platformio. Thank you for help!
